#!/bin/bash
# status-dump.sh — Talonnet status snapshot for Zion
# Outputs short form to terminal, detailed form to GitHub (Zion branch)
# Usage: ./status-dump.sh
# Repo: TheHandlerProject/talon-scripts  Branch: Zion  Folder: status-dump/

set -euo pipefail

REPO_DIR="${HOME}/talon-scripts"
STATUS_DIR="${REPO_DIR}/status-dump"
OUTPUT_FILE="${STATUS_DIR}/talonnet-status.md"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"
HOSTNAME_VAL="$(hostname)"
UPTIME_VAL="$(uptime -p)"

# ---------------------------------------------------------------------------
# SHORT FORM — printed to terminal immediately
# ---------------------------------------------------------------------------
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "  TALONNET STATUS — ${TIMESTAMP}"
echo "  Host: ${HOSTNAME_VAL}   Uptime: ${UPTIME_VAL}"
echo "╚══════════════════════════════════════════════════╝"
echo ""

echo "── DOCKER CONTAINERS ──"
docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null || echo "  Docker not running or no containers."
echo ""

echo "── MEMORY ──"
free -h | grep Mem
echo ""

echo "── DISK (/) ──"
df -h / | tail -1
echo ""

echo "── NETWORK ──"
ip -br addr 2>/dev/null || echo "  ip command unavailable."
echo ""

echo "── DNS ──"
grep "^nameserver" /etc/resolv.conf 2>/dev/null || echo "  /etc/resolv.conf missing or no nameservers."
echo ""

# ---------------------------------------------------------------------------
# FULL FORM — written to file and pushed to GitHub
# ---------------------------------------------------------------------------

# Ensure repo and status-dump folder exist
if [ ! -d "${REPO_DIR}/.git" ]; then
    echo "ERROR: ${REPO_DIR} is not a git repo. Cannot push to GitHub." >&2
    exit 1
fi

mkdir -p "${STATUS_DIR}"

# Gather extended data
CPU_MODEL="$(grep "model name" /proc/cpuinfo 2>/dev/null | head -1 | cut -d: -f2 | xargs || echo 'unknown')"
RAM_TOTAL="$(free -h | awk '/^Mem:/{print $2}')"
RAM_USED="$(free -h | awk '/^Mem:/{print $3}')"
RAM_FREE="$(free -h | awk '/^Mem:/{print $4}')"
DISK_INFO="$(df -h / | awk 'NR==2{print $2 " total, " $3 " used (" $5 ")"}')"

DOCKER_TABLE="$(docker ps -a --format "| \`{{.Names}}\` | {{.Image}} | {{.Status}} | {{.Ports}} |" 2>/dev/null || echo '| — | docker unavailable | — | — |')"

DOCKER_RESTARTS="$(docker ps -a --format "{{.Names}}" 2>/dev/null | while read -r name; do
    restarts="$(docker inspect "${name}" --format='{{.RestartCount}}' 2>/dev/null || echo '?')"
    last_start="$(docker inspect "${name}" --format='{{.State.StartedAt}}' 2>/dev/null || echo '?')"
    printf "| \`%s\` | %s | %s |\n" "${name}" "${restarts}" "${last_start}"
done || echo '| — | — | — |')"

FAILED_SERVICES="$(systemctl list-units --type=service --state=failed --no-pager --no-legend 2>/dev/null | awk '{print "| `" $1 "` | " $2 " | " $3 " |"}' || echo '| — | — | — |')"

NET_DETAIL="$(ip addr 2>/dev/null || echo 'unavailable')"
DNS_SERVERS="$(grep "^nameserver" /etc/resolv.conf 2>/dev/null | awk '{print $2}' | tr '\n' '  ' || echo 'unavailable')"

RECENT_LOGS="$(journalctl -p err -n 20 --no-pager 2>/dev/null || echo 'journalctl unavailable')"

# Write markdown file
cat > "${OUTPUT_FILE}" << MDEOF
# Talonnet Status Report

**Generated:** ${TIMESTAMP}
**Host:** ${HOSTNAME_VAL}
**Uptime:** ${UPTIME_VAL}

---

## Hardware

| Component | Value |
|-----------|-------|
| CPU | ${CPU_MODEL} |
| RAM Total | ${RAM_TOTAL} |
| RAM Used | ${RAM_USED} |
| RAM Free | ${RAM_FREE} |
| Disk (/) | ${DISK_INFO} |

---

## Docker Containers

| Name | Image | Status | Ports |
|------|-------|--------|-------|
${DOCKER_TABLE}

### Restart Counts

| Container | Restarts | Last Started |
|-----------|----------|--------------|
${DOCKER_RESTARTS}

---

## Systemd — Failed Services

| Unit | Load | Active |
|------|------|--------|
${FAILED_SERVICES}

---

## Network

### Interfaces
\`\`\`
${NET_DETAIL}
\`\`\`

### DNS Nameservers
${DNS_SERVERS}

---

## Recent System Errors (last 20)

\`\`\`
${RECENT_LOGS}
\`\`\`

---

*Generated by status-dump.sh on ${HOSTNAME_VAL}*
MDEOF

echo "✔ Status file written to: ${OUTPUT_FILE}"

# Push to GitHub
cd "${REPO_DIR}"
git fetch origin Zion 2>/dev/null || true
git checkout Zion 2>/dev/null || git checkout -b Zion
git add "${OUTPUT_FILE}"
git commit -m "status-dump: ${TIMESTAMP}" || echo "  Nothing new to commit."
git push origin Zion
echo "✔ Pushed to GitHub (Zion branch)"
echo ""
